spring.application.name=recommendation-service

spring.datasource.url=jdbc:postgresql://localhost:5432/recommendations
spring.datasource.username=service_recommendations
spring.datasource.password=seva8090
spring.jpa.hibernate.ddl-auto = validate
spring.jpa.show-sql=true
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml

application.recommendations-db.url=jdbc:h2:file:./transaction
show.sql.queries = true

