spring.application.name=recommendation-service

spring.datasource.url=jdbc:postgresql://localhost:5432/recommendations
spring.datasource.username=service_recommendations
spring.datasource.password=seva8090
spring.jpa.hibernate.ddl-auto = validate
spring.jpa.show-sql=true
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml

application.recommendations-db.url=jdbc:h2:file:./transaction;ACCESS_MODE_DATA=r
show.sql.queries = true

# ==========================================
# REDIS & CACHE CONFIGURATION
# ==========================================
# Connection settings for distributed cache storage
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Switching Spring Cache abstraction to Redis provider
spring.cache.type=redis

# TTL (Time to live) default
spring.cache.redis.time-to-live= 10m

# Prevent caching of null values
spring.cache.redis.cache-null-values=false
