-- liquibase formatted sql

-- changeset fedenistov:Создаём таблицу
CREATE TABLE rule_entity_test(
    id bigint generated by default as identity,
    product_name VARCHAR ,
    product_id uuid ,
    product_text VARCHAR ,
    rule jsonb ,
    primary key (id)
);

